const PDFDocument = require('pdfkit');
const fs = require('fs');

/**
 * Generates a professional PDF invoice
 * @param {Object} invoice - Invoice data from database
 * @param {Object} client - Client data
 * @param {Object} user - Business owner data
 * @returns {Promise<Buffer>} - PDF file as buffer
 */
const generateInvoicePDF = (invoice, client, user) => {
  return new Promise((resolve, reject) => {
    try {
      // Create a new PDF document
      const doc = new PDFDocument({ margin: 50 });
      const buffers = [];
      
      // Collect PDF chunks as they're generated
      doc.on('data', buffers.push.bind(buffers));
      doc.on('end', () => resolve(Buffer.concat(buffers)));
      doc.on('error', reject);

      // ===== HEADER SECTION =====
      // Business information
      doc.fontSize(20).font('Helvetica-Bold')
         .text(user.companyName || 'InvoiceFlow', 50, 50);
      
      doc.fontSize(10).font('Helvetica')
         .text(user.email || '', 50, 75)
         .text(user.address || 'Professional Invoicing', 50, 90);

      // Invoice title and details
      doc.fontSize(24).font('Helvetica-Bold')
         .text('INVOICE', 400, 50, { align: 'right' });
      
      doc.fontSize(10).font('Helvetica')
         .text(`Invoice #: ${invoice.invoiceNumber}`, 400, 80, { align: 'right' })
         .text(`Issue Date: ${new Date(invoice.issueDate).toLocaleDateString()}`, 400, 95, { align: 'right' })
         .text(`Due Date: ${new Date(invoice.dueDate).toLocaleDateString()}`, 400, 110, { align: 'right' });

      // ===== CLIENT INFORMATION =====
      doc.fontSize(12).font('Helvetica-Bold')
         .text('Bill To:', 50, 150);
      
      doc.fontSize(10).font('Helvetica')
         .text(client.name, 50, 170)
         .text(client.email, 50, 185);
      
      if (client.address) {
        const address = client.address;
        doc.text(`${address.street || ''}`, 50, 200)
           .text(`${address.city || ''} ${address.state || ''} ${address.zipCode || ''}`, 50, 215);
      }

      // ===== LINE ITEMS TABLE =====
      const tableTop = 260;
      
      // Table headers
      doc.fontSize(10).font('Helvetica-Bold')
         .text('Description', 50, tableTop)
         .text('Qty', 350, tableTop)
         .text('Price', 400, tableTop)
         .text('Amount', 450, tableTop);
      
      // Table separator
      doc.moveTo(50, tableTop + 15).lineTo(550, tableTop + 15).stroke();

      // Line items
      let currentY = tableTop + 30;
      invoice.items.forEach((item, index) => {
        if (currentY > 650) { // Prevent overflow to new page
          doc.addPage();
          currentY = 50;
        }
        
        const amount = item.quantity * item.price;
        
        doc.fontSize(9).font('Helvetica')
           .text(item.description, 50, currentY, { width: 280 })
           .text(item.quantity.toString(), 350, currentY)
           .text(`$${item.price.toFixed(2)}`, 400, currentY)
           .text(`$${amount.toFixed(2)}`, 450, currentY);
        
        currentY += 20;
      });

      // ===== TOTALS SECTION =====
      const totalsY = Math.max(currentY + 20, 600);
      
      doc.fontSize(10).font('Helvetica')
         .text('Subtotal:', 400, totalsY)
         .text(`$${invoice.subtotal.toFixed(2)}`, 450, totalsY);
      
      if (invoice.taxRate > 0) {
        doc.text(`Tax (${invoice.taxRate}%):`, 400, totalsY + 15)
           .text(`$${invoice.taxAmount.toFixed(2)}`, 450, totalsY + 15);
      }
      
      doc.fontSize(12).font('Helvetica-Bold')
         .text('Total:', 400, totalsY + 35)
         .text(`$${invoice.total.toFixed(2)}`, 450, totalsY + 35);

      // ===== NOTES SECTION =====
      if (invoice.notes) {
        const notesY = totalsY + 60;
        doc.fontSize(10).font('Helvetica-Bold')
           .text('Notes:', 50, notesY);
        
        doc.fontSize(9).font('Helvetica')
           .text(invoice.notes, 50, notesY + 15, { width: 500 });
      }

      // ===== FOOTER =====
      const footerY = 750;
      doc.fontSize(8).font('Helvetica')
         .text('Thank you for your business!', 50, footerY, { align: 'center' })
         .text('Generated by InvoiceFlow', 50, footerY + 12, { align: 'center' });

      // Finalize PDF
      doc.end();

    } catch (error) {
      reject(error);
    }
  });
};

module.exports = { generateInvoicePDF };